import type { DownloadItem, ProjectVersion } from "../types";

export function collectFiles(versions: ProjectVersion[], folder: string): DownloadItem[] {
    const items: DownloadItem[] = [];
    for (const version of versions) {
        for (const file of version.files) {
            if (file.primary) {
                items.push({ url: file.url, filename: file.filename, folder, size: file.size });
            }
        }
    }
    return items;
}

export function generateProperties(props: Record<string, string | number | boolean>): string {
    const lines = [
        "#Minecraft server properties",
        `#Generated by Minecraft-Server-Builder on ${new Date().toISOString()}`,
        ""
    ];
    for (const [key, value] of Object.entries(props)) {
        lines.push(`${key}=${value}`);
    }
    return lines.join("\n");
}